### ISSUE TITLE
Remove the single builder package per project restriction

### ISSUE THREAD

**Issue by tombentley** [sundrio/sundrio#105]
The limitation on having a single builder package per project is annoying and has a distorting effect on how code would otherwise be packaged. It would be great if this restriction were removed.

**Comment by iocanel** [comment]
@tombentley: The rationale behind the builder package is to prevent runtime dependency to sundrio. The idea was that instead of depending on yet another jar, to generate everything it needs side by side with the fluent builders.

There are options in the @Buildable annotation to instruct sundrio *NOT* to generate the builder package and reuse those classes from the package of your choice. This allows you to either reuse the package from `sundrio-core` jar, or any other jar that already has those classes generated. For example: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L209 reuses the package that has been generated as part of another project.

**Comment by iocanel** [comment]
As there is nothing more to do. I am closing this one.
