### ISSUE TITLE
Add SupportedVersion annotation to all processors

### ISSUE THREAD

**Issue by iocanel** [sundrio/sundrio#120]

**Comment by EXTERNALCOREWORKS** [comment]
Hi, Im facing the same exception using Kubernetes API Client V9.0.0, and apparently this problem got introduced by the sundrio version picked by them since Kubernetes API Client V 3.0. Is there a plan to fix this one up ? 
I know its a harmless message but should be good to prevent it from appearing in the logs. Thanks in advance.

**Comment by iocanel** [comment]
This has been addressed almost a year now, closing.
