### ISSUE TITLE
Better binary compatibility in generated code

### ISSUE THREAD

**Issue by tombentley** [sundrio/sundrio#150]
Both strimzi and fabric8 use sundrio to generate fluent builders. Strimzi makes use of Fabric8's builder package `io.fabric8.kubernetes.api.builder`. That, in turn, requires Strimzi to use a compatible version of sundrio as was used for the version of sundrio used for the fabric8 release we depend on. The cause of binary incompatibility is usually the visitables field in the builder baseclass which the Strimzi builders inherit from. 

* Does sundrio offer any guarantee of binary compatibility between different minor or micro versions? If so, could this be better communicated in the docs? If not, could such a guarantee be offered?
* Perhaps such guarantees would be easier to offer if the field was private and subclasses accessed it via methods? (I honestly have no idea if this would work in practice).

**Comment by iocanel** [comment]
@tombentley: Micro releases are meant to be bugfix releases. Micro versions indicate potential breakage in the generated code. 

Since your generated code injerits fabric8 classes, its best be aligned with fabric8. 
However, this is only mandatory whenever classes under `io.fabric8.kubernetes.api.builder`change which is not that often. I think that such changes should be reflected by a change in that major version, other changes affecting generated code should be reflected by minor version bump and all the rest should be micor releases.

Now, this assumes that we get past 1.0.0 release. Personally, I'd like to slow things down in sundrio and then do a `1.0.0`, but the are a couple of things I'd like to address first.

**Comment by tombentley** [comment]
Thanks for the clarification @iocanel.
