### ISSUE TITLE
Add explicit class as type parameter

### ISSUE THREAD

**Issue by rhuss** [sundrio/sundrio#37]
Thanks to generics' type erasure there is no (clean) way to get the genric class parameter during runtime (i've seen people parsing the the toString() output, though ;-).

This means, that e.g. https://github.com/sundrio/sundrio/blob/master/core/src/main/java/io/sundr/builder/BaseFluent.java#L70  is called for every object, regardless whether the visitior was parameterized for this object or not. So, class cast exception will occur all the time.

The typical solution to this is to explicitely provide the visitors connected class explicitely (e.g. by a `Visitor.getType()` and then check that before calling the visitor. Makes it easier to debug, too and makes one feel a bit less dirty ;-)

**Comment by iocanel** [comment]
Here are some thoughts I had in the past about it:

1. Add a getType() method and check against that.
2. Generate an abstract visitor per builder (which would grant access to the parameter during runtime).
3. Use reflection to check type rather than try and throw a class cast.

The main reason I don't like (1) is that I want visitor to be a functional interface and work with lamdas too.

So what we could do is either go with (3) or with a hybrid solution.

A hybrid solution could be adding an additional interface say ``TypedVisitor`` that provides the ``getType()``. BaseFluent could then check if visitor is a typed visitor and do (1) or not and do (3).

**Comment by rhuss** [comment]
Sounds all good to me. 

Maybe we could use https://github.com/FasterXML/java-classmate , too, it is supposed to be able to resolve generic types despite 'type erasure' ? (e.g. as in https://gist.github.com/yunspace/930d4d40a787a1f6a7d1)

If we would have the generic type with which the Visitor has been created one could then use `Class.isAssignableFrom()` before calling `accept()` ....

The problem with throwing and catching class casts is not only an aesthetical one, I had Jolokia users (where it did sth similar) which had some generic interceptor for exceptions applied for monitoring, so they wouldn't be happy here :)

I could give it a try, if you think its the way to go ....

**Comment by iocanel** [comment]
I have (3) implemented exception free, so we could make it hybrid with (1) and have the best of both world

**Comment by rhuss** [comment]
cool, sounds awesome ! ;-)

**Comment by iocanel** [comment]
@rhuss: I borrowed the idea of "super type token" that is used by classmate and it seem to work pretty nice without the need to expose additional methods to the user. I'll release so that we can try it out.

**Comment by rhuss** [comment]
@iocanel I don't understand a word, but yeah, looks impressive ;-) 

I will happily try it out. Will the Kubernetes Model be updated, too ?

**Comment by iocanel** [comment]
@rhuss: We need to update the model manually.

**Comment by iocanel** [comment]
I think that we can close this now
