### ISSUE TITLE
[Builder Annotation] : Builder methods generated `withFooFoo` for fields with same type name but different packages

### ISSUE THREAD

**Issue by rohanKanojia** [sundrio/sundrio#437]
Follow up to #425

I upgraded to newer sundrio version and I can no longer see the error. Thanks.

However, I see some additional changes in builder methods which I did not expect:
```diff
--- a/kubernetes-model-generator/openshift-model-hive/src/test/java/io/fabric8/openshift/api/model/hive/v1/ClusterPoolTest.java
+++ b/kubernetes-model-generator/openshift-model-hive/src/test/java/io/fabric8/openshift/api/model/hive/v1/ClusterPoolTest.java
@@ -67,12 +67,12 @@ class ClusterPoolTest {
         .withName("openshift-4-6")
         .endImageSetRef()
         .withNewPlatform()
-        .withNewAws()
+        .withNewAwsAws()
         .withNewCredentialsSecretRef()
         .withName("hive-team-aws-creds")
         .endCredentialsSecretRef()
         .withRegion("us-east-1")
-        .endAws()
+        .endAwsAws()
         .endPlatform()
         .withNewPullSecretRef()
         .withName("hive-team-pull-secret")
```

Shall I create a new issue about this? You can inspect the changes  affected in this commit [4db1082d4e670c3cca69b51ed5b69439ece86afc](https://github.com/rohanKanojia/kubernetes-client/commit/4db1082d4e670c3cca69b51ed5b69439ece86afc)

_Originally posted by @rohanKanojia in https://github.com/sundrio/sundrio/issues/425#issuecomment-1778465943_

**Comment by shawkins** [comment]
Several observations:
- the naming logic is effectively choosing the first instance type to be dominant / imported / unqualified.  The other instance types will be named based upon the first part of their package name that differs.  The property name is appended to that.  So that is why aws is repeated.
- however that is somewhat arbitrarily promoting a type - since none of them are in the same packages as the class whose fluent is being created, it's not clear what the convention is.
- introducing other subtle naming (for example in the shapes test a foo.v1 package) or typing (using parameterized Circle siblings) fails either to complie or fails the tests.
