### ISSUE TITLE
Visitable.accept visits all Visitor instances regardless of the type

### ISSUE THREAD

**Issue by manusa** [sundrio/sundrio#438]
Changes in #431 seem to be causing an issue with Visitors

With the new changes in:

https://github.com/sundrio/sundrio/blob/836ebeabed8f708f792ffac001a43e154852f0ea/core/src/main/java/io/sundr/builder/Visitable.java#L77-L91

Visitors are now called regardless of the matching type.

Seems like the double for-loop is a mistake or something left from previous iterations.

/cc @shawkins @iocanel

**Comment by iocanel** [comment]
I am not sure that I completely understand what the problem is, so let me try to provide some details on how it should work (or at least how I remember it should work).

The `accept` method on a `Visitable` is meant to `accept` any type of `Visitor` regardless of type. The `Visitor` may or may not `visit` the current `Visitable` but is forwarded/`accept` to all child `Visitable`. 
For ordering reasons the forwarding process is done in two iterations:

1st pass we forward/`accept` all `Visitors` with matching types
2st pass we forward/`accept` all `Visitor` items with non-matching types

Why ? Because we want directly matching `Visitor` to always be applied before any other `Visitor`.
Why ? Becuase a directly matching `Visitor` may populate additional `Visitable` items.

So, the highlighted double for loop seems needed to me. Also, accepting all types of `Visitor` seems justified to me too.
Maybe its the `canVisit` that is not respected and the `visit` method being called out of place?
What exactly is the side effect?

**Comment by manusa** [comment]
OK; I might have misdiagnosed the issue then. However, we still have a problem here. Still digging into it.

The test that revealed this (among others) was https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricherTest.java#L59

For some reason the visitor is being triggered multiple times.

**Comment by manusa** [comment]
So the following test illustrates the problem.

In this case, the visitor is called 4 times instead of the expected 1 (or at least this is how it behaved before).

The problem might be in the `getVisitablaMap` part instead.

**Comment by shawkins** [comment]
@manusa this should be unrelated to the recent change - all that did was move the existing logic.  At least for me if I change Visitable and Basefluent back to what they were, you still see things visited multiple times.

**Comment by manusa** [comment]
I'm not sure if you've checked https://github.com/fabric8io/kubernetes-client/pull/5558 (maybe I should port it to this repo though)

It illustrates the issue, it works with 6.9.0 but fails with 6.9.1.

As you say, your changes just move around code. However, it's my impression that some of the changes regarding the use of the Map and its entries seem to be causing the visiting logic to become recursive.

**Comment by shawkins** [comment]
> It illustrates the issue, it works with 6.9.0 but fails with 6.9.1.

It's something else that has changed with 6.9.1 - if you revert BaseFluent / Visitable in 6.9.1, you see 4 visitations.  If you forward port the changes in 6.9.0 you see 1 visitation.

**Comment by manusa** [comment]
> If you forward port the changes in 6.9.0 you see 1 visitation.

You mean just bumping the Sundrio version or something else?

**Comment by shawkins** [comment]
> You mean just bumping the Sundrio version or something else?

I've found the issue.  There's a place in the generated fluents where the visitable tracking is not correct.

**Comment by manusa** [comment]
I'm trying to implement a test for this repo, hopefully will send a PR in a few minutes

**Comment by shawkins** [comment]
@manusa this works for me https://github.com/sundrio/sundrio/pull/440

**Comment by manusa** [comment]
I finally managed to create the reproducer test, nothing like a good weekend's rest :)
